import type { APIRoute } from 'astro';
import { TypeSafeClient, noul, score } from '@typesafe-ai/sdk';

export const prerender = false;

const MAX_CHARS = 8000;

const SLOP_LEVELS = [
  'Unmistakably human: specific lived detail, uneven rhythm, opinions, quirks or mess',
  'Probably human: ordinary prose, maybe polished, but it has a voice',
  'Genuinely ambiguous: competent and clean, no strong tell either way',
  'Probably AI: smooth, balanced, oddly tidy structure and hedged phrasing',
  'Unmistakably AI slop: padded, symmetrical, listicle cadence, says little at length',
] as const;

// One score drives the verdict; the nouls are the receipts.
const QUESTIONS = {
  slop: score('How much does this text read as generated by an AI language model rather than written by a person?', SLOP_LEVELS),
  hedging: noul('Does the text hedge or qualify constantly instead of committing to a claim?'),
  filler: noul('Is the text padded with words that add no information?'),
  cliches: noul('Does the text lean on AI-assistant cliches such as "delve", "tapestry", "it is important to note", or "in today\'s fast-paced world"?'),
  specifics: noul('Does the text contain concrete specifics — names, numbers, dates or first-hand detail — that a generic generator would not invent?'),
} as const;

// Built on first request so a missing key is a clean 500, not a boot crash.
let client: TypeSafeClient | undefined;
function getClient() {
  const apiKey = import.meta.env.TYPESAFE_API_KEY ?? process.env.TYPESAFE_API_KEY;
  if (!apiKey) throw new Error('TYPESAFE_API_KEY is not set. Copy .env.example to .env and add your key.');
  client ??= new TypeSafeClient({ apiKey, timeout: 30_000 });
  return client;
}

export const POST: APIRoute = async ({ request }) => {
  let text: unknown;
  try {
    ({ text } = await request.json());
  } catch {
    return json({ error: 'Send JSON with a "text" field.' }, 400);
  }

  if (typeof text !== 'string' || text.trim().length < 40) {
    return json({ error: 'Give me at least a couple of sentences to work with.' }, 400);
  }

  try {
    const response = await getClient().systemOne({
      state: { text: text.slice(0, MAX_CHARS) },
      questions: QUESTIONS,
    });

    const { slop, hedging, filler, cliches, specifics } = response.answers;

    return json({
      // 0-100, where 100 is maximum slop.
      slop: Math.round((slop.score / (SLOP_LEVELS.length - 1)) * 100),
      confidence: slop.confidence,
      verdict: SLOP_LEVELS[Math.round(slop.score)] ?? '',
      // Keys match the signal rows rendered in index.astro.
      signals: [
        { key: 'hedging', value: hedging.noul },
        { key: 'filler', value: filler.noul },
        { key: 'cliches', value: cliches.noul },
        { key: 'specifics', value: specifics.noul },
      ],
    });
  } catch (error) {
    console.error('systemOne failed:', error);
    const status = (error as { status?: number }).status;
    if (status === 401 || status === undefined) {
      return json({ error: 'Server is missing a valid TYPESAFE_API_KEY.' }, 500);
    }
    if (status === 429) return json({ error: 'Rate limited by JEV. Give it a moment.' }, 429);
    return json({ error: 'JEV could not be reached. Try again.' }, 502);
  }
};

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json' },
  });
}
